### PR TITLE
Support loading state (no UI)

### PR DESCRIPTION
**Pull request by walkerrandolphsmith**
Add a FETCHING and FETCHED media actions.
Assert that the FETCHING action is yielded and the FETCHED action is contained in the array.
Create a reducer that handles the two action types by setting a boolean loading state.
Expose that state in MediaGalleryPage connect.

### CODE REVIEW

**Comment by walkerrandolphsmith** [comment]
This was my first exposure to redux-saga. I have been using redux-thunks and feeling the side-effect pain. Cool to see how declarative this can be. Let me know if this is wrong. I would love to know some pointers on sagas.

**Review by rowlandekemezie — COMMENTED** [review]
@walkerrandolphsmith I'm delighted you found this helpful.Your contribution is elegant. I wanted to merge your PR but want to know your thought on this. Instead of having a separate reducer for loading, shouldn't we add the `isLoading` property as part of the payload for the action creators(requests) and the success action type on the reducers? That way, we can now have loading component in the UI. What's your take?

**Comment by walkerrandolphsmith** [comment]
First I love the naming convention isLoading. I almost changed my name. I think I see where you are going with this let me make some tweaks!

**Comment by walkerrandolphsmith** [comment]
Do you expect something like this 

```
 yield [
      put({ type: types.SHUTTER_VIDEOS_SUCCESS, videos, isLoading: false }),
      put({ type: types.SELECTED_VIDEO, video: videos[0] }),
      put({ type: types.FLICKR_IMAGES_SUCCESS, images, isLoading: false }),
      put({ type: types.SELECTED_IMAGE, image: images[0] })
    ];
```

?

**Comment by rowlandekemezie** [comment]
Yea. That makes sense. Would you prefer having a presentational component(Loading) to handle the spinner on the UI?

**Comment by walkerrandolphsmith** [comment]
Yeah I think that makes sense. Although this [article](http://moduscreate.com/how-to-use-image-placeholders-in-react-native/) is about react native, I believe there is information related to the user experience of waiting on media to load that is useful.

I am a bit stuck on how to move forward with implementing what we discussed in the previous posts. It seems that if there is no loading reducer than the action must be handled by the imageReducer or the videoReducer. I added `isLoading` to the payload of actions that are handled by both, but each of the reducers manages its own set of the state tree. Would there be two isLoading states?

**Comment by rowlandekemezie** [comment]
I see. For MVP, it should but there could be some refactor around the working implementation. I feel that having the action creators with `isLoading` property set to `true` and setting same to false in the `success` case of each of the reducers would suffice, at least for now.

**Comment by walkerrandolphsmith** [comment]
@andela-rekemezie would you like to pair on this so we can move forward with your ideas.

**Comment by rowlandekemezie** [comment]
@walkerrandolphsmith That makes sense. However, I don't have a must be idea. In the meantime, can you please push your code

**Comment by rowlandekemezie** [comment]
@walkerrandolphsmith Can we close this issue today? Let me know if you still need to pair.

**Comment by walkerrandolphsmith** [comment]
Yeah I have been preoccupied in the past couple of days. I will work on this later this afternoon and try to wrap it up!

**Pull request closed without merging**
